
# This file is automatically generated, you probably don't want to edit this

rciOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rciOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pre = NULL,
            post = NULL,
            reliability = 0.8,
            useClinicalChange = FALSE,
            method = "critC",
            normalMean = NULL,
            normalSd = NULL,
            clinicalMean = NULL,
            clinicalSd = NULL, ...) {

            super$initialize(
                package="LET",
                name="rci",
                requiresData=TRUE,
                ...)

            private$..pre <- jmvcore::OptionVariable$new(
                "pre",
                pre,
                suggested=list(
                    "continuous"))
            private$..post <- jmvcore::OptionVariable$new(
                "post",
                post,
                suggested=list(
                    "continuous"))
            private$..reliability <- jmvcore::OptionNumber$new(
                "reliability",
                reliability,
                default=0.8)
            private$..useClinicalChange <- jmvcore::OptionBool$new(
                "useClinicalChange",
                useClinicalChange,
                default=FALSE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "critA",
                    "critB",
                    "critC",
                    "critD"),
                default="critC")
            private$..normalMean <- jmvcore::OptionNumber$new(
                "normalMean",
                normalMean)
            private$..normalSd <- jmvcore::OptionNumber$new(
                "normalSd",
                normalSd)
            private$..clinicalMean <- jmvcore::OptionNumber$new(
                "clinicalMean",
                clinicalMean)
            private$..clinicalSd <- jmvcore::OptionNumber$new(
                "clinicalSd",
                clinicalSd)

            self$.addOption(private$..pre)
            self$.addOption(private$..post)
            self$.addOption(private$..reliability)
            self$.addOption(private$..useClinicalChange)
            self$.addOption(private$..method)
            self$.addOption(private$..normalMean)
            self$.addOption(private$..normalSd)
            self$.addOption(private$..clinicalMean)
            self$.addOption(private$..clinicalSd)
        }),
    active = list(
        pre = function() private$..pre$value,
        post = function() private$..post$value,
        reliability = function() private$..reliability$value,
        useClinicalChange = function() private$..useClinicalChange$value,
        method = function() private$..method$value,
        normalMean = function() private$..normalMean$value,
        normalSd = function() private$..normalSd$value,
        clinicalMean = function() private$..clinicalMean$value,
        clinicalSd = function() private$..clinicalSd$value),
    private = list(
        ..pre = NA,
        ..post = NA,
        ..reliability = NA,
        ..useClinicalChange = NA,
        ..method = NA,
        ..normalMean = NA,
        ..normalSd = NA,
        ..clinicalMean = NA,
        ..clinicalSd = NA)
)

rciResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rciResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Reliable Change")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Reliable Change"))}))

rciBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rciBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "LET",
                name = "rci",
                version = c(1,0,0),
                options = options,
                results = rciResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Reliable Change
#'
#' 
#' @param data .
#' @param pre .
#' @param post .
#' @param reliability .
#' @param useClinicalChange .
#' @param method .
#' @param normalMean .
#' @param normalSd .
#' @param clinicalMean .
#' @param clinicalSd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
rci <- function(
    data,
    pre,
    post,
    reliability = 0.8,
    useClinicalChange = FALSE,
    method = "critC",
    normalMean,
    normalSd,
    clinicalMean,
    clinicalSd) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rci requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pre)) pre <- jmvcore::resolveQuo(jmvcore::enquo(pre))
    if ( ! missing(post)) post <- jmvcore::resolveQuo(jmvcore::enquo(post))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pre), pre, NULL),
            `if`( ! missing(post), post, NULL))


    options <- rciOptions$new(
        pre = pre,
        post = post,
        reliability = reliability,
        useClinicalChange = useClinicalChange,
        method = method,
        normalMean = normalMean,
        normalSd = normalSd,
        clinicalMean = clinicalMean,
        clinicalSd = clinicalSd)

    analysis <- rciClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

