name: Build jamovi Module
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build jamovi module
        uses: jamovi/jamovi-action@master
        with:
          command: build

      - name: Upload .jmo
        uses: actions/upload-artifact@v4
        with:
          name: windows-module
          path: ./*.jmo
