name: Build Windows Module
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Build Module
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org", jamovi = "https://repo.jamovi.org"))
          # We install pkgbuild because it's a reliable, standard R tool
          install.packages(c('jmvcore', 'jmvtools', 'pkgbuild'))
          library(jmvtools)
          # 1. Prepare the jamovi-specific R files
          jmvtools::prepare()
          # 2. Build the package into a .zip file in the current folder
          pkgbuild::build(binary = TRUE, dest_path = ".")
        shell: Rscript {0}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-module
          path: "./*.zip"
